/*++

Copyright (c) Microsoft Corporation.  All rights reserved.

_WdfVersionBuild_

Module Name:

    WdfCollection.h

Abstract:

    This is the interface to the collection object

Environment:

    kernel mode only

Revision History:

--*/

//
// NOTE: This header is generated by stubwork.  Please make any 
//       modifications to the corresponding template files 
//       (.x or .y) and use stubwork to regenerate the header
//

#ifndef _WDFCOLLECTION_H_
#define _WDFCOLLECTION_H_

#ifndef WDF_EXTERN_C
  #ifdef __cplusplus
    #define WDF_EXTERN_C       extern "C"
    #define WDF_EXTERN_C_START extern "C" {
    #define WDF_EXTERN_C_END   }
  #else
    #define WDF_EXTERN_C
    #define WDF_EXTERN_C_START
    #define WDF_EXTERN_C_END
  #endif
#endif

WDF_EXTERN_C_START



#if (NTDDI_VERSION >= NTDDI_WIN2K)



//
// WDF Function: WdfCollectionCreate
//
_Must_inspect_result_
_IRQL_requires_max_(DISPATCH_LEVEL)
NTSTATUS
WdfCollectionCreate(
    _In_opt_
    PWDF_OBJECT_ATTRIBUTES CollectionAttributes,
    _Out_
    WDFCOLLECTION* Collection
    );

//
// WDF Function: WdfCollectionGetCount
//
_IRQL_requires_max_(DISPATCH_LEVEL)
ULONG
WdfCollectionGetCount(
    _In_
    WDFCOLLECTION Collection
    );

//
// WDF Function: WdfCollectionAdd
//
_Must_inspect_result_
_IRQL_requires_max_(DISPATCH_LEVEL)
NTSTATUS
WdfCollectionAdd(
    _In_
    WDFCOLLECTION Collection,
    _In_
    WDFOBJECT Object
    );

//
// WDF Function: WdfCollectionRemove
//
_IRQL_requires_max_(DISPATCH_LEVEL)
VOID
WdfCollectionRemove(
    _In_
    WDFCOLLECTION Collection,
    _In_
    WDFOBJECT Item
    );

//
// WDF Function: WdfCollectionRemoveItem
//
_IRQL_requires_max_(DISPATCH_LEVEL)
VOID
WdfCollectionRemoveItem(
    _In_
    WDFCOLLECTION Collection,
    _In_
    ULONG Index
    );

//
// WDF Function: WdfCollectionGetItem
//
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFOBJECT
WdfCollectionGetItem(
    _In_
    WDFCOLLECTION Collection,
    _In_
    ULONG Index
    );

//
// WDF Function: WdfCollectionGetFirstItem
//
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFOBJECT
WdfCollectionGetFirstItem(
    _In_
    WDFCOLLECTION Collection
    );

//
// WDF Function: WdfCollectionGetLastItem
//
_IRQL_requires_max_(DISPATCH_LEVEL)
WDFOBJECT
WdfCollectionGetLastItem(
    _In_
    WDFCOLLECTION Collection
    );



#endif // (NTDDI_VERSION >= NTDDI_WIN2K)


WDF_EXTERN_C_END

#endif // _WDFCOLLECTION_H_

